'use client'

import { useMemo, useState } from 'react'
import { newYouTubeAssistant, type AssistantLifecycle, type State } from '../lib/lifecycle'

const stages = ['Brief','Prepared setup','Access & plan','Isolated trial','Activation','Dashboard / audit']
const promptExample='Each Monday, research emerging Ethereum topics and prepare three video concepts for review. Never publish without approval.'
const stateLabel:Record<State,string>={draft:'DRAFT',reviewed:'REVIEWED',entitled:'ENTITLED',provisioned:'PROVISIONED','test-passed':'TESTED',active:'ACTIVE'}

export default function Home(){
 const [brief,setBrief]=useState(''); const [assistant,setAssistant]=useState<AssistantLifecycle|null>(null); const [,refresh]=useState(0); const [error,setError]=useState(''); const [ack,setAck]=useState(false); const [trialOutput,setTrialOutput]=useState<string[]>([])
 const snap=assistant?.snapshot
 const stage=!assistant?'brief':!snap?'brief':snap.state==='draft'?'brief':snap.state==='reviewed'?'prepared':snap.state==='entitled'?'access':snap.state==='provisioned'?'trial':snap.state==='test-passed'?'activation':'dashboard'
 const stageIndex=Math.max(0,stages.findIndex(x=>x.toLowerCase().startsWith(stage)))
 const act=(fn:()=>void)=>{try{setError('');fn();refresh(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'Action blocked')}}
 const prepare=()=>{if(brief.trim().length<12){setError('Add a little more detail so we can prepare a useful setup.');return} setAssistant(newYouTubeAssistant('demo-'+Date.now()));setError('')}
 const runTrial=()=>act(()=>{assistant!.passTrial();setTrialOutput(['L2 rollups for Ethereum developers','What account abstraction changes for creators','A practical guide to safer agent permissions'])})
 const audit=useMemo(()=>snap?.audit.slice().reverse()??[],[snap])
 return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">LM</span> LegitMate</div><div className="top-meta">Commissioning desk · v0.1 / sandbox</div></header><div className="main">
  <section className="intro"><div><div className="eyebrow">A managed assistant, properly commissioned</div><h1>Describe the work.<br/><em>We prepare</em> the assistant.</h1><p className="intro-copy">Start with a working setup, not a blank screen. Review the proposed tools, boundaries, and activation decision before anything can act.</p></div><div className="registration mono">FILE 001 / YC-OPS<strong>Prepared for creator operations</strong>09 SEP 2026<br/>Provider-free walkthrough</div></section>
  <section className="desk" aria-label="Assistant commissioning workflow"><nav className="stages" aria-label="Commissioning stages"><div className="stage-label mono">The desk / {String(Math.min(stageIndex+1,6)).padStart(2,'0')} of 06</div>{stages.map((s,i)=><div className={`stage ${i===stageIndex?'active':''} ${i<stageIndex?'done':''}`} key={s}><span className="stage-number">{i<stageIndex?'✓':`0${i+1}`}</span><span>{s}<span className="stage-state">{i<stageIndex?'complete':i===stageIndex?'in review':'up next'}</span></span></div>)}</nav>
   <div className="content">{error&&<div className="blocked" role="alert"><strong>Action blocked.</strong> {error}</div>}
    {stage==='brief'&&<><div className="eyebrow">01 / Intake</div><h2>Start with a working setup,<br/>not a blank screen.</h2><p className="lede">Tell us what the assistant should handle, who it serves, and where you want the final say. We turn it into a prepared configuration you can inspect.</p><div className="prompt"><textarea aria-label="Describe the work" value={brief} onChange={e=>{setBrief(e.target.value);setError('')}} placeholder="For example: I run a YouTube channel about..."/><div className="mono" style={{color:'var(--muted)'}}>{brief.length} characters · plain language is fine</div></div><div className="actions"><button className="secondary" onClick={()=>setBrief(promptExample)}>Use Ethereum creator example</button><button className="primary" onClick={prepare}>Prepare my setup →</button></div><div className="rule"/><div className="eyebrow">Other desks / concepts only</div><div className="preset-row"><div className="preset"><span className="concept">CONCEPT / 02</span><h3>WhatsApp concierge</h3><p>Draft replies and reminders for review. Not active in this walkthrough.</p></div><div className="preset"><span className="concept">CONCEPT / 03</span><h3>Business Operator</h3><p>Prepare recurring office work. Not active in this walkthrough.</p></div></div></>}
    {stage==='prepared'&&<><span className="stamp">{stateLabel[snap!.state]} / REVIEW</span><h2>Your setup, on paper.</h2><p className="lede">A bounded YouTube Creator Operations assistant, prepared from your brief. Requested access is not granted access.</p><div className="config-grid"><div className="config-box"><h3>Requested permissions</h3><ul>{snap!.requestedPermissions.map(p=><li key={p}>{p}</li>)}</ul></div><div className="config-box"><h3>Approved permissions</h3><ul><li>None yet</li><li>Nothing connected</li><li>Human approval required</li><li>Publishing is blocked</li></ul></div></div><div className="notice"><strong>Guardrail / always on</strong>No account connection, publishing, messaging, or purchasing occurs in this provider-free demo.</div><div className="actions"><button className="secondary" onClick={()=>setAssistant(null)}>← Edit brief</button><button className="primary" onClick={()=>act(()=>assistant!.review())}>Review access & plan →</button></div></>}
    {stage==='access'&&<><div className="eyebrow">03 / Entitlement</div><h2>Choose the room.<br/>Keep the keys.</h2><p className="lede">Payment and activation are separate decisions. This step uses a deterministic simulated entitlement and sandbox workspace.</p><div className="plan"><div><strong>Creator operations / sandbox</strong><small>One prepared workspace · no provider connection</small></div><div className="price">$0 <small>simulated</small></div></div><div className="checks"><div className="check">✓ <span>Configuration reviewed</span></div><div className="check">✓ <span>Entitlement is simulated and local</span></div><div className="check">✓ <span>Activation remains explicit</span></div></div><div className="notice"><strong>SIMULATED SANDBOX / HACKATHON</strong>No payment is taken and no external workspace is created.</div><div className="actions"><button className="secondary" onClick={()=>act(()=>{ /* no backwards domain transition */ })}>← Review setup</button><button className="primary" onClick={()=>act(()=>{assistant!.entitle();assistant!.provision()})}>Provision sandbox →</button></div></>}
    {stage==='trial'&&<><div className="eyebrow">04 / Prove the boundary</div><h2>A quiet, isolated trial.</h2><p className="lede">The server-owned trial is read-only and non-publishing. It demonstrates a useful result without connecting an account.</p><div className="prompt"><div className="mono">TRIAL TASK / READ-ONLY / {snap!.provisionedResource}</div><h3>Prepare three Ethereum video concepts for a developer audience.</h3><div className="rule"/>{trialOutput.length===0?<div className="blocked"><strong>Ready to run.</strong> No external message, edit, or publish call will be made.</div>:<ul className="trial-output">{trialOutput.map(x=><li key={x}>{x}</li>)}</ul>}</div><div className="actions"><button className="primary" onClick={runTrial}>Run isolated trial →</button></div></>}
    {stage==='activation'&&<><span className="stamp">TESTED / AWAITING APPROVAL</span><h2>Ready for your approval.</h2><p className="lede">The trial passed. Activation is a separate decision and remains blocked until you acknowledge the exact boundary below.</p><div className="notice"><strong>Activation receipt</strong><br/>This sandbox may run the prepared, non-publishing workflow. No account is connected and no content can be published in this demo.</div><label className="ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I understand this setup is simulated, isolated, and inactive until I approve it.</label><div className="actions"><button className="secondary" onClick={()=>setAck(false)}>Keep inactive</button><button className="primary" disabled={!ack} onClick={()=>act(()=>{assistant!.approve();assistant!.activate()})}>Approve and activate →</button></div></>}
    {stage==='dashboard'&&<><div className="dashboard-head"><div><span className="stamp">ACTIVE / SANDBOX</span><h2>The desk is ready.</h2></div><div className="status">● ACTIVE · ISOLATED</div></div><p className="lede">Your assistant is active in a local sandbox. It has no connected account and cannot publish content.</p><div className="audit"><div className="mono" style={{margin:'13px 0'}}>Recorded audit / latest first</div>{audit.map((e,i)=><div className="audit-row" key={i}><span className="mono">{new Date(e.at).toLocaleTimeString()}</span><span>{e.type==='approval'?'Activation approved explicitly':`${e.from} → ${e.to}`}</span><span className="mono row-state">recorded</span></div>)}</div><div className="blocked"><strong>Current boundary.</strong> No account is connected. No content has been published. Real provider integrations are not part of this preview.</div><div className="actions"><button className="secondary" onClick={()=>{setAssistant(null);setBrief('');setAck(false);setTrialOutput([])}}>Start another brief</button><button className="primary" onClick={()=>setAssistant(newYouTubeAssistant('demo-'+Date.now()))}>New prepared setup</button></div></>}
   </div></section></div></main>
}
