'use client'

import { useEffect, useState } from 'react'

type Stage = 'brief' | 'prepared' | 'access' | 'trial' | 'dashboard'
const stages: { key: Stage; label: string }[] = [
  { key: 'brief', label: 'Brief' }, { key: 'prepared', label: 'Prepared setup' },
  { key: 'access', label: 'Access & plan' }, { key: 'trial', label: 'Isolated trial' }, { key: 'dashboard', label: 'Dashboard / audit' },
]
const youtubePrompt = 'I need help running my YouTube channel: research topics, build a content calendar, draft titles and descriptions, and keep publishing checklists tidy. Never publish without my approval.'

export default function Home() {
  const [stage, setStage] = useState<Stage>('brief')
  const [brief, setBrief] = useState('')
  const [error, setError] = useState('')
  const [trialDone, setTrialDone] = useState(false)
  const [activationAcknowledged, setActivationAcknowledged] = useState(false)
  const [sessionStartedAt, setSessionStartedAt] = useState<Date | null>(null)
  const [trialCompletedAt, setTrialCompletedAt] = useState<Date | null>(null)
  const [activationApprovedAt, setActivationApprovedAt] = useState<Date | null>(null)
  useEffect(() => { setSessionStartedAt(new Date()); const saved = window.localStorage.getItem('legitmate-stage'); if (saved && stages.some(s => s.key === saved)) setStage(saved as Stage) }, [])
  const move = (next: Stage) => { setError(''); setActivationAcknowledged(false); setStage(next); window.localStorage.setItem('legitmate-stage', next) }
  const completeTrial = () => { setTrialDone(true); setTrialCompletedAt(new Date()) }
  const activateSandbox = () => { if (!activationAcknowledged) return; setActivationApprovedAt(new Date()); move('dashboard') }
  const auditTime = (value: Date | null) => value ? value.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : 'pending'
  const prepare = () => { if (brief.trim().length < 12) { setError('Add a little more detail so we can prepare a useful setup.'); return }; move('prepared') }
  const index = stages.findIndex(s => s.key === stage)
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">LM</span> LegitMate</div><div className="top-meta">Commissioning desk · v0.1 / sandbox</div></header>
    <div className="main">
      <section className="intro"><div><div className="eyebrow">A managed assistant, properly commissioned</div><h1>Describe the work.<br /><em>We prepare</em> the assistant.</h1><p className="intro-copy">A calm way to turn a job into a reviewable setup, before anything is connected or allowed to act.</p></div><div className="registration mono">FILE 001 / YC-OPS<strong>Prepared for creator operations</strong>09 SEP 2026<br />Provider-free walkthrough</div></section>
      <section className="desk" aria-label="Assistant commissioning workflow">
        <nav className="stages" aria-label="Commissioning stages"><div className="stage-label mono">The desk / {String(index + 1).padStart(2, '0')} of 05</div>{stages.map((s, i) => <div className={`stage ${s.key === stage ? 'active' : ''} ${i < index ? 'done' : ''}`} key={s.key}><span className="stage-number">{i < index ? '✓' : `0${i + 1}`}</span><span>{s.label}<span className="stage-state">{i < index ? 'complete' : s.key === stage ? 'in review' : 'up next'}</span></span></div>)}</nav>
        <div className="content">
          {stage === 'brief' && <><div className="eyebrow">01 / Intake</div><h2>Start with a working setup,<br />not a blank screen.</h2><p className="lede">Tell us what the assistant should handle, who it serves, and where you want the final say. We will turn it into a prepared brief you can inspect.</p><div className="prompt"><textarea aria-label="Describe the work" value={brief} onChange={e => { setBrief(e.target.value); setError('') }} placeholder="For example: I run a YouTube channel about..." /> <div className="mono" style={{ color: 'var(--muted)' }}>{brief.length} characters · plain language is fine</div></div>{error && <div className="blocked" role="alert">{error}</div>}<div className="actions"><button className="secondary" onClick={() => setBrief(youtubePrompt)}>Use YouTube creator example</button><button className="primary" onClick={prepare}>Prepare my setup →</button></div><div className="rule" /><div className="eyebrow">Other desks / concepts only</div><div className="preset-row"><div className="preset"><span className="concept">CONCEPT / 02</span><h3>WhatsApp concierge</h3><p>Sort incoming questions and draft replies for review. Not active in this walkthrough.</p></div><div className="preset"><span className="concept">CONCEPT / 03</span><h3>Business Operator</h3><p>Keep recurring operations visible and orderly. Not active in this walkthrough.</p></div></div></>}
          {stage === 'prepared' && <><span className="stamp">PREPARED / REVIEW</span><h2>Your setup, on paper.</h2><p className="lede">We translated your brief into a bounded YouTube Creator Operations assistant. Review what is requested and what is approved — they are intentionally different.</p><div className="config-grid"><div className="config-box"><h3>Requested permissions</h3><ul><li>Read channel analytics</li><li>Read video metadata</li><li>Draft titles, descriptions & tags</li><li>Draft publishing checklists</li></ul></div><div className="config-box"><h3>Approved permissions</h3><ul><li>None yet</li><li>Nothing connected</li><li>Human approval required</li><li>Publishing is blocked</li></ul></div></div><div className="notice"><strong>Guardrail / always on</strong>This assistant can prepare drafts and research notes in an isolated workspace. It cannot publish, message, purchase, or connect an account in this MVP.</div><div className="actions"><button className="secondary" onClick={() => move('brief')}>← Edit brief</button><button className="primary" onClick={() => move('access')}>Review access & plan →</button></div></>}
          {stage === 'access' && <><div className="eyebrow">03 / Entitlement</div><h2>Choose the room.<br />Keep the keys.</h2><p className="lede">Payment and activation are separate decisions. This preview uses a simulated entitlement and provisioning flow for the hackathon.</p><div className="plan"><div><strong>Creator operations / sandbox</strong><small>One prepared workspace · no provider connection</small></div><div className="price">$0 <small>simulated</small></div></div><div className="checks"><div className="check">✓ <span>Prepared configuration saved locally</span></div><div className="check">✓ <span>Trial is isolated and non-publishing</span></div><div className="check">✓ <span>Activation remains explicit</span></div></div><div className="notice"><strong>Simulated sandbox / hackathon</strong>No payment is taken, no entitlement is real, and no assistant is provisioned outside this browser.</div><div className="actions"><button className="secondary" onClick={() => move('prepared')}>← Back to setup</button><button className="primary" onClick={() => move('trial')}>Provision sandbox →</button></div></>}
          {stage === 'trial' && <><div className="eyebrow">04 / Prove the boundary</div><h2>A quiet, isolated trial.</h2><p className="lede">Try a representative task without touching a provider. This gives you a useful output and shows exactly where the boundary holds.</p><div className="prompt"><div className="mono">TRIAL TASK / 001</div><h3 style={{ fontSize: 22, fontWeight: 500 }}>Draft three video angles for an audience learning sustainable home cooking.</h3><div className="rule" /><div className="checks"><div className="check">✓ <span>Research note prepared: seasonal, low-waste recipes</span></div><div className="check">✓ <span>Three draft angles queued for your review</span></div><div className="check">✓ <span>No channel read, write, or publish call made</span></div></div>{trialDone && <div className="stamp">TRIAL COMPLETE / NO SIDE EFFECTS</div>}</div>{!trialDone && <div className="blocked"><strong>Blocked by design.</strong> This trial cannot publish content or connect an account. That is the point.</div>}<div className="actions">{!trialDone ? <><button className="secondary" onClick={() => move('access')}>← Back</button><button className="primary" onClick={() => setTrialDone(true)}>Run isolated trial →</button></> : <><button className="secondary" onClick={() => move('prepared')}>Review setup</button><button className="primary" onClick={() => move('dashboard')}>Activate sandbox →</button></>}</div></>}
          {stage === 'dashboard' && <><div className="dashboard-head"><div><span className="stamp">ACTIVATED / SANDBOX</span><h2>The desk is ready.</h2></div><div className="status">● ACTIVE · ISOLATED</div></div><p className="lede">Your YouTube Creator Operations assistant is active in a local sandbox. It has no connected account and cannot publish content.</p><div className="audit"><div className="mono" style={{ margin: '13px 0' }}>Append-only audit / latest first</div><div className="audit-row"><span className="mono">09:14:08</span><span>Activation approved explicitly</span><span className="mono row-state">recorded</span></div><div className="audit-row"><span className="mono">09:13:42</span><span>Isolated trial completed</span><span className="mono row-state">no side effects</span></div><div className="audit-row"><span className="mono">09:12:10</span><span>Sandbox entitlement simulated</span><span className="mono row-state">local only</span></div><div className="audit-row"><span className="mono">09:10:55</span><span>Prepared setup reviewed</span><span className="mono row-state">recorded</span></div></div><div className="blocked"><strong>Current boundary.</strong> No account is connected. No content has been published. Real provider integrations are not part of this preview.</div><div className="actions"><button className="secondary" onClick={() => move('brief')}>Start another brief</button><button className="primary" onClick={() => move('prepared')}>Inspect configuration</button></div></>}
        </div>
      </section>
    </div>
  </main>
}
