export const FREE_TRANSITION_RECIPES = [
  'avatar-group',
  'button-loader',
  'card-resize',
  'card-tilt',
  'checkbox-check',
  'confetti-burst',
  'error-state-shake',
  'icon-swap',
  'like-button',
  'matrix-loader',
  'menu-dropdown',
  'modal',
  'notification-badge',
  'number-pop-in',
  'page-side-by-side',
  'panel-reveal',
  'plus-menu-morph',
  'skeleton-reveal',
  'spinner',
  'streaming-text',
  'success-check',
  'tabs-sliding',
  'text-states-swap',
  'texts-reveal',
  'toast',
  'toggle-switch',
  'tooltip',
  'upload-progress',
  'video-morph',
  'voice-waveform',
  'word-rotate',
  'writing-text',
] as const

export type FreeTransitionRecipe = typeof FREE_TRANSITION_RECIPES[number]

export const LEGITMATE_MOTION_ASSIGNMENTS: Record<FreeTransitionRecipe, string> = {
  'avatar-group': 'Connected integrations or collaborators when real identities exist',
  'button-loader': 'Launch, proof, Graph, and lifecycle request buttons',
  'card-resize': 'Bounded instance and receipt detail expansion',
  'card-tilt': 'Pointer-only specialist-card emphasis with restrained depth',
  'checkbox-check': 'Specialist and capability selection confirmation',
  'confetti-burst': 'Verified deployment success only',
  'error-state-shake': 'One-shot user-correctable action or validation failure',
  'icon-swap': 'Theme, sound, copy, retry, disclosure, and lifecycle controls',
  'like-button': 'Saved/favorite specialist affordance when persistence exists',
  'matrix-loader': 'Terminal or diagnostic execution state',
  'menu-dropdown': 'Wallet and secondary instance actions',
  'modal': 'Destructive instance deletion and explicit review boundaries',
  'notification-badge': 'Verified capability or intervention-required count',
  'number-pop-in': 'Specialist, catalog, selected-capability, and instance counts',
  'page-side-by-side': 'Progressive instance list-to-detail continuity',
  'panel-reveal': 'Commissioning steps, catalog states, receipts, and diagnostics',
  'plus-menu-morph': 'Compact mobile secondary-action disclosure',
  'skeleton-reveal': 'Catalog and instance data loading without false progress',
  'spinner': 'Short indeterminate requests with persistent status copy',
  'streaming-text': 'Real streamed agent output only',
  'success-check': 'Verified configuration, proof, integration, and action success',
  'tabs-sliding': 'Catalog kind filters and genuine tab sets',
  'text-states-swap': 'Server-driven async phase and control-label changes',
  'texts-reveal': 'One-time editorial heading entry, never polling content',
  'toast': 'Non-blocking completion and recovery messages',
  'toggle-switch': 'Theme and sound preferences',
  'tooltip': 'Supplemental control explanations, never required instructions',
  'upload-progress': 'Real file-transfer progress when byte progress is available',
  'video-morph': 'Future verified demo media surface; dormant until real media exists',
  'voice-waveform': 'Future live voice input/output; dormant until audio exists',
  'word-rotate': 'Dormant; rotating marketing copy is not appropriate in the operational flow',
  'writing-text': 'Real incremental agent response rendering only',
}

export const MOTION_TOKENS = {
  duration: { fast: 120, base: 180, slow: 260 },
  distance: { small: 4, medium: 8, panel: 18 },
  easing: {
    standard: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    exit: 'cubic-bezier(0.4, 0, 1, 1)',
    spring: 'linear(0, 0.45 12%, 0.82 28%, 1.03 54%, 1 100%)',
  },
} as const
