import type { Metadata } from 'next'
import Link from 'next/link'
import { productOffers } from '../../lib/product-offers'

export const metadata: Metadata = { title: 'LegitClub Products | AI Workspaces, Search, Video & Decks', description: 'Four managed systems for operating, finding demand, publishing short-form video, and building presentation decks.', alternates: { canonical: 'https://mate.legitclub.com/products' }, openGraph: { title: 'LegitClub Products', description: 'Specialist workspaces and managed systems for search, video, and presentations.', url: 'https://mate.legitclub.com/products', type: 'website' } }

export default function ProductsPage() {
  return <main className="products-page"><nav className="products-nav"><Link href="/" className="products-brand"><span>LC</span> LegitClub</Link><div><Link href="/products">Products</Link><Link href="/seo-services">Search</Link><Link href="/short-form-video">Video</Link><Link href="/presentation-design">Decks</Link></div></nav><header className="products-hero"><p className="products-kicker">LEGITCLUB / PRODUCT SYSTEMS</p><h1>Specialists for the work<br /><em>that has to ship.</em></h1><p>LegitClub combines specialist judgment with software workflows. Choose an owned agent workspace or a managed production system for search, short-form video, and presentations.</p></header><section className="products-grid">{productOffers.map((product, index) => <article key={product.slug} className={`product-card product-${product.accent}`}><div><span>0{index + 1}</span><b>{product.label}</b></div><h2>{product.name}</h2><p>{product.description}</p><small>{product.audience}</small><Link href={product.href}>Explore {product.name} →</Link></article>)}</section><section className="products-fit"><p className="products-kicker">HOW THEY CONNECT</p><div><h2>Build the message.<br />Earn discovery.<br />Publish the proof.</h2><p>Deck Studio clarifies the story. Search Systems maps the demand. Short-Form Studio distributes the strongest ideas. Agent Workspaces give the team a persistent operator for the work around them.</p></div></section><footer className="products-footer"><span>© LegitClub</span><a href="mailto:hello@legitclub.com?subject=LegitClub%20product%20brief">Bring us the brief →</a></footer></main>
}
